modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues"
license="All rights reserved"

[[mods]]
    modId="thutcore"
    version="99.99.99"
    displayName="Thut Core"
    authors="Thutmose"
    description='''
    This is a library of shared functionality for my mods.

    This is the version embedded into Pokécube, so use that for
    the more reliable version number
    '''
    
[[mods]]
    modId="thutcrafts"
    version="${file.jarVersion}"
    displayName="Thut Crafts"
    authors="Thutmose"
    description='''
    Tech Demo mod for testing the elevator mod updates.
    '''
    
[[mods]]
    modId="thut_wearables"
    version="${file.jarVersion}"
    displayName="Thut Wearables"
    authors="Thutmose"
    description='''
    Accessories Slots for Minecraft!

    This is the version embedded into Pokécube.
    '''

[[mods]]
    modId="thut_bling"
    version="${file.jarVersion}"
    displayName="Thut Bling"
    authors="Thutmose"
    description='''
    Bling for Thut Wearables!

    This is the version embedded into Pokécube.
    '''

[[mods]]
    modId="pokecube"
    version="${file.jarVersion}"
    displayName="Pokécube Core"
    authors="Thutmose"
    description='''
    Core mod for Pokécube Functionality
    '''

[[mods]]
    modId="pokecube_mobs"
    version="${file.jarVersion}"
    displayName="Pokécube Mobs"
    authors="Thutmose"
    description='''
    General mobs provider for Pokécube
    '''

[[mods]]
    modId="pokecube_adventures"
    version="${file.jarVersion}"
    displayName="Pokécube Revival"
    authors="Thutmose"
    description='''
    Additional Features for Pokécube..
    '''

[[mods]]
    modId="pokecube_legends"
    version="${file.jarVersion}"
    displayName="Pokécube Legends"
    authors="NelkGames, Thutmose"
    description='''
    Legendary Spawning mechanics for Pokécube..
    '''
    
[[dependencies.thutcore]]
    modId="minecraft"
    mandatory=true
    versionRange="version_mc"
    ordering="NONE"
    side="BOTH"