modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues"

[[mods]]
    modId="thutcore"
    version="version_thutcore"
    displayName="Thut Core"
    authors="Thutmose"
    description='''
    This is a library of shared functionality for my mods.

    This is the version embedded into pokecube, so use that for
    the more reliable version number
    '''
    
[[mods]]
    modId="thutcrafts"
    version="${file.jarVersion}"
    displayName="Thut Crafts"
    authors="Thutmose"
    description='''
    Tech Demo mod for testing the elevator mod updates.
    '''
    
[[mods]]
    modId="thut_wearables"
    version="${file.jarVersion}"
    displayName="Thut Wearables"
    authors="Thutmose"
    description='''
    Accessories Slots for Minecraft!

    This is the version embedded into pokecube.
    '''

[[mods]]
    modId="thut_bling"
    version="${file.jarVersion}"
    displayName="Thut Bling"
    authors="Thutmose"
    description='''
    Bling for Thut Wearables!

    This is the version embedded into pokecube.
    '''

[[mods]]
    modId="pokecube"
    version="${file.jarVersion}"
    displayName="Pokecube Core"
    authors="Thutmose"
    description='''
    Core mod for Pokecube Functionality
    '''

[[mods]]
    modId="pokecube_mobs"
    version="${file.jarVersion}"
    displayName="Pokecube Mobs"
    authors="Thutmose"
    description='''
    General mobs provider for Pokecube
    '''

[[mods]]
    modId="pokecube_adventures"
    version="${file.jarVersion}"
    displayName="Pokécube Revival"
    authors="Thutmose"
    description='''
    Additional Features for Pokécube..
    '''

[[mods]]
    modId="pokecube_legends"
    version="${file.jarVersion}"
    displayName="Pokécube Legends"
    authors="NelkGames, Thutmose"
    description='''
    Legendary Spawning mechanics for Pokécube..
    '''
    
[[dependencies.thutcore]]
    modId="minecraft"
    mandatory=true
    versionRange="version_mc"
    ordering="NONE"
    side="BOTH"